ProjectPythia/pythia-foundations

.github/workflows/deploy.yaml
This makes the book accessible at the following URL: foundations.projectpythia.org
Unless folks want a different URL, I will merge this once the CI checks are complete. 
Cc @brian-rose
=> Add CNAME record

.github/workflows/deploy.yaml, README.md, environment.yml, landing-page.md, requirements.txt
The environment file includes `pre-commit`. This should help with running the linting pre-commit hooks.
=> Add conda development env file

_config.yml, environment.yml, preamble/how-to-contribute.md
Jupyter book has a built-in extra dropdown button for "suggest edits" per our discussion in today's meeting. This is also a chance for anyone in @ProjectPythia/education to see if you're able to push to my PR. I can always wipe out your change if it works. Attached is a screenshot of the important setting beneath the body text of your PR to enable collaboration from project maintainers. This is enabled by default for me, and if it's disabled then external maintainers will not have default write access to your branch on your fork. Otherwise we might have a permissions issue somewhere? Screenshot attached:
=> Add suggest edits to top repo button

_config.yml, _toc.yml, preamble/how-to-contribute.md, preamble/template.ipynb
* Convert the #33 xarray notebook to a template and add it to the preamble
* Add some body to `how-to-contribute` arround it
Drawing inspiration from [our AMS template](https://github.com/Unidata/pyaos-ams-2021/blob/master/instructors/notebook-template/Template.ipynb) and the existing xarray notebook, we've diagrammed out the structure of our notebook template. We will add demonstrative body text, code cells, opinions on tying together the sections, and more shortly. For the moment, feel free to provide feedback on the organization and formatting of sections, headers, etc.
Sidenote: @ProjectPythia/infrastructure let's make a hackathon label!
cc: @mgrover1 @ktyle
=> Create notebook template for contributors

environment.yml
Just adds `jupyterlab` to our `environment.yml` file.
This is not strictly necessary for building the book from sources, but I would argue that it's an essential ingredient if we're using this environment for developing new content, and/or directing users to this environment for running our example notebooks.
=> Add jupyterlab to pythia-book-dev environment

_config.yml
Modifies the footer displayed at the bottom of every page:
- a link to Project Pythia portal home (https://projectpythia.org) embedded in the text `By the Project Pythia community`
- replace rambling text with link to the Foundations contributors guide page
=> Improve page footer: links to Pythia portal and Contributors guide

_toc.yml, appendix/how-to-contribute.md, environment.yml
This should close #91 and get our build working again:
- Migrate the TOC to the new format required by JupyterBook 0.11, as described [here](https://executablebooks.org/en/latest/updates/2021-06-18-update-toc.html)
- Fix the broken link identified in #91
=> Migrate TOC to new format

_config.yml
This *might* get the google analytics working for the Foundations site.
I noticed that my other JupyterBook site (which has working analytics) wrapped the ID in double quotes:
https://github.com/brian-rose/ClimateLaboratoryBook/blob/87801650d5f2e374494d8ccfc955b2a3b3000254/_config.yml#L45
This is consistent with the JupyterBook config reference, which shows double quotes: 
https://jupyterbook.org/customize/config.html
I tried using double quotes here, but prettier insisted on changing them to single quotes.
=> Wrap analytics id in quotes

appendix/how-to-contribute.md
=> Remove obsolete text about README page from How to Contribute

.pre-commit-config.yaml, _config.yml, _templates/layout.html, _templates/sbt-sidebar-footer.html, _templates/sbt-sidebar-nav.html, _templates/sidebar-logo.html
Closes #105 
This PR is intended for using a workaround to get Foundations Book's Google Analytics working until this [pydata-sphinx-theme PR ](https://github.com/pydata/pydata-sphinx-theme/pull/439) gets merged and released. 
Brief Explanation of Solution:
- `google_analytics_id ` under `html` tag in `_config.yml` is disabled. Instead, `templates_path` under `sphinx` tag as a `config` item into this file.
- In `_templates/layout.html`, we still extend `sphinx_book_theme/layout.html` that is the default `jupyter-book` that we are already using here.
- In that layout file, we are manually adding the Google Analytics snippet as [suggested by Google](https://developers.google.com/analytics/devguides/collection/gtagjs) to the extrahead before body.
- The other html files in the `_templates` …
=> Google Analytics Workaround Until Pydata Fix Gets Released

_templates/layout.html
Google Analytics did not start working yet since we forgot to add this script:
`<script async src="https://www.googletagmanager.com/gtag/js?id=G-G57FLM9M46"></script>`
which this PR adds
=> Google Analytics: Add forgotten async script

.github/workflows/deploy.yaml, .github/workflows/preview-book.yaml
This PR 
(1) replaces the custom [ProjectPythia/actions/comment-netlify-preview-in-pr](https://github.com/ProjectPythia/actions/tree/main/comment-netlify-preview-in-pr) GitHub action with a combination of actively maintained actions. 
(2) Updates an existing comment (with a preview URL) instead of creating a new comment for each git push. 
Note: This PR needs to be merged for changes in the preview-book workflow https://github.com/ProjectPythia/pythia-foundations/blob/96fb41393d79da002d376aa9a8ca5d49401db6ef/.github/workflows/preview-book.yaml to take effect...
=> Update Jupyter Book Preview Workflow

.github/workflows/deploy.yaml, .github/workflows/preview-book.yaml
Addresses https://github.com/ProjectPythia/pythia-foundations/pull/139#issuecomment-921190200. 
GitHub restricts permissions granted to the default `GITHUB_TOKEN`:
> With the exception of GITHUB_TOKEN, secrets are not passed to the runner when a workflow is triggered from a forked repository. The permissions for the GITHUB_TOKEN in forked repositories is read-only. For more information, see "Authenticating with the GITHUB_TOKEN."
See the [docs for more](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#triggering-new-workflows-using-a-personal-access-token). 
To circumvent this restriction, I moved the workflow steps that need `GTIHUB_TOKEN` with write permissions to the `preview-book` workflow which is trigger on `on: workflow_run:`
=> Fix write permission issue that arises during pull_request events

appendix/how-to-contribute.md, foundations/conda.md
This PR finishes continues to address https://github.com/ProjectPythia/projectpythia.github.io/issues/162 by adding instructions for updating the conda environment in two places:
- Pythia Foundations contributor's guide
- list of useful conda commands in the conda section of Foundations
I also changed the formatting of all the bash shell snippets in the Contributor's Guide to remove the `$ ` prefix from each line. Happy to hear dissenting voices on this, but they interfere with the JupyterBook feature of copying the working example to the clipboard with one click, because the `$ ` characters are copied along with the executable command.
=> Add documentation on conda update --all

.github/workflows/preview-book.yaml
https://github.com/ProjectPythia/pythia-foundations/pull/149 introduced a new version of `github-script` action. This new version includes [breaking changes](https://github.com/actions/github-script#breaking-changes-in-v5) that cause the [CI to fail](https://github.com/ProjectPythia/pythia-foundations/runs/3716520538?check_suite_focus=true)
=> Fix breaking changes in github-script v5

_config.yml, appendix/how-to-contribute.md
Adding the Google form to the footer of each foundations book page AND to the contributor's guide.
=> Add Google Form to footer

core/data-formats/netcdf-cf.ipynb
One of the resources links used `[...][...)` by mistake so the link didn't render properly.
=> Fix link format in the netCDF lesson

preamble/how-to-use.md
This PR partially addressed #127; it updates the how-to-use document to address conda environment setup.
=> Update how-to-use document to provide information on conda env setup

foundations/quickstart.ipynb
Addresses user feedback in #226.
I tried to clarify the instructions in the Quickstart notebook on where to find the Binder link.
Also fixed an unrelated typo that I found in that notebook.
=> Clarify how to find the Binder link

preamble/how-to-use.md
There is a broken link to Matplotlib-Basics in the preamble.
=> fix link in preamble

foundations/github/basic-git.md, foundations/github/git-branches.md, foundations/github/github-cloning-forking.md, foundations/github/github-issues.md, foundations/github/github-setup-advanced.md
All these sections said "All Previous GitHub Chapters" instead of specifics for their prereqs. This PR addresses that.
Related to #214
=> update prereqs in GitHub sections

core/overview.md
I've had a go at expanding the [overview](https://foundations.projectpythia.org/core/overview.html) of the Python geoscience software stack.
The content I've added has been adapted from [this page](https://pyaos.github.io/stack/) on the PyAOS website. Incorporating some of the PyAOS content into Pythia Foundations is something we've been [discussing](https://github.com/ProjectPythia/projectpythia.github.io/discussions/210) for a while.
=> Add overview of geoscience stack

_toc.yml, foundations/getting-started-github.md, foundations/github/basic-git.md, foundations/github/contribute-to-pythia.md, foundations/github/git-branches.md, foundations/github/github-cloning-forking.md, foundations/github/github-issues.md, foundations/github/github-pull-request.md, foundations/github/github-repos.md, foundations/github/github-setup-advanced.md, foundations/github/github-workflows.md, foundations/github/what-is-github.md
This PR does the following:
- Uses more consistent logos through the GitHub sections (including the landing page)
- Fixes the list of topics and links on the landing page
- Removes the placeholder "Advanced topics" notebook from the TOC (the notebook file is still there in the repo in case we want to populate it later)
- Renames the "Advanced GitHub Setup" section to "Configuring your GitHub account" (sounds less scary)
=> More polishing of GitHub sections

_toc.yml, core/xarray.md, core/xarray/computation-masking.ipynb, core/xarray/enso-xarray.ipynb, core/xarray/xarray-intro.ipynb
This PR adds the Xarray logo to the section landing page, removes the "under construction" message (addressing #231), and renames the first notebook to `xarray-intro.ipynb` (updating internal links appropriately)
=> Clean up Xarray landing page

environment.yml
The environment that conda (or mamba) creates from this file on Windows
does not work; importing 'pythia_datasets' results in a cryptic error:
ImportError: DLL load failed while importing shell: The specified procedure could not be found.
It seems there is some incompatibility between 'pywin32', a dependency
of 'jupyter_core' on Windows, and 'appdirs' (a dependency of
pythia_dataset's dependency 'pooch'), at least under Python 3.8.
Fix this by lifting the version constrain on the 'python' package. This
creates an environment with Python 3.10, where importing
'pythia_datasets' works correctly.
Closes: https://github.com/ProjectPythia/pythia-foundations/issues/277
=> environment.yml: do not constrain 'python' to 3.8

foundations/jupyterlab.ipynb
Corrected the spelling of "Running" in the section "Running JupyterLab Notebooks" in "Getting Started with Jupyter," and clarified the text in the first paragraph.
In the text clarification, I used HTML Entities. These render slightly different in Jupyter Lab then they do in the generated HTML.
=> Fixed spelling error and clarified text.

core/numpy/numpy-broadcasting.ipynb, foundations/github/git-branches.md
This PR updates the "References" section of git-branches.md to make references display as links. It also deletes a redundant link in the "Resources and references" section of numpy-broadcasting.ipynb and changes the heading level of that section to "##" instead of "###".
It didn't seem like there was consistent styling of the "Resources and references" sections throughout the book. For example, pages use "Resources and references", "References", or "Additional Resources" as the section title. Some of these sections use numbered lists while others use bulleted lists. I tried to make the changes I made blend in with the rest of the book, but if more consistency is wanted I can create an issue for that.
=> Updates references to display as links

foundations/getting-started-jupyter.ipynb
Fixes #328. Note that the new SVG logo is quite a bit smaller than the PNG that we linked to before, but IMHO it's ok.
=> Update link to Jupyter logo

core/xarray/computation-masking.ipynb
I'm submitting this, my 1st ProjectPythia PR, per the instructions in the Pythia Foundations Book, in the section "Contribute to Project Pythia via Github".
https://foundations.projectpythia.org/foundations/github/contribute-to-pythia.html
BTW, this sections says "Let’s add the content tag and open this one as a draft for now", but I don't see a way to add tags in github.
=> Mention that SST is called tos in the model

README.md
Adds link to the Zenodo page for the foundations book release. 
Points to consider: badge link needs to be updated with new releases, still need to add prominent how to cite section.
Related to #309 and #344
=> Add Zenodo badge to README

environment.yml
Seeing if we can now remove two likely-obsolete version pins from the environment file.
The scipy pin was introduced recently in https://github.com/ProjectPythia/pythia-foundations/pull/414 waiting until the next Cartopy release. That has happened so we shouldn't need the pin anymore.
The other pin is much older, dating back to the first introduction of the Cartopy notebook https://github.com/ProjectPythia/pythia-foundations/pull/24. I'm not sure the original reason this was needed, but I suspect it's obsolete now.
Testing to see if everything works!
=> Remove old version pins from environment

core/matplotlib/annotations-colorbars-layouts.ipynb
This PR should get the link-checker back to health.
=> Fix link to matplotlib annotations examples

README.md, core/numpy/numpy-basics.ipynb, core/overview.md
The current introduction talks about a `stack`. I understand the intention of teaching new students a lingo, but no overview of libraries is given. My current edits can help students get an understanding of what content follows.
Please also note that I added "... libraries **(or packages)**", because the following tutorials use these terms interchangeably, and I think this is a good place to equate these terms.
=> Language edits in the Introduction section of the Core Package Overview

core/xarray/computation-masking.ipynb, core/xarray/dask-arrays-xarray.ipynb, foundations/conda.md
With the new sphinx theme, admonitions are called like 
```
```{admonition} Info
:class: tip
In the above code example, we are extract ...
```
The HTML `<div> ...` version was causing the issues. This is isolated to these two files and doesn't require an overall theme adjustment.
Closes https://github.com/ProjectPythia/sphinx-pythia-theme/issues/64
=> Change admonitions

core/numpy/numpy-basics.ipynb
This pull request updates the array slicing syntax documentation. The original syntax notation 'array[start:stop[:step]]' could be misinterpreted as suggesting the step parameter is nested within the stop parameter. This update simplifies the notation to 'array[start:stop:step]', clearly delineating each parameter, enhancing readability and reducing potential confusion for users.
=> Clarify Array Slicing Syntax from 'array[start:stop[:step]]' to 'array[start:stop:step]'

core/numpy/numpy-basics.ipynb, foundations/github/git-branches.md
Changes done to git-branches.md:
-  added note about touch command which does not work on windows
- fixed typo
- rewrote Complete Workflow section in Git Branches for clarity
=> Git Branches section edits

foundations/jupyter.md
There are several differences between a notebook and a script, to avoid potential confusion (say if someone copied notebook cells into a script) I wanted to highlight the two biggest differences in code syntax between the two.
=> Jupyter notebooks vs Python scripts syntax

foundations/conda.md, foundations/jupyter.md, foundations/terminal.md
=> Update installation instructions to use miniforge/mamba

foundations/conda.md
Incorporate @brian-rose suggested edit in #491
=> Additional text to justify use of conda-forge

core/data-formats/netcdf-cf.ipynb, core/datetime/datetime.ipynb
=> Fix broken link about lunar day, and remove dead link to NASA dataset interoperability

.github/workflows/publish-book.yaml, .github/workflows/trigger-preview.yaml
This needs doing for consistency with https://github.com/ProjectPythia/cookbook-actions/pull/135
Publishing of the preview is expected to fail here.
=> Remove cname argument to deploy-book workflow

core/pandas/pandas.ipynb, core/xarray/computation-masking.ipynb, foundations/how-to-run-python.md
The nightly build has been failing for months due to link problems. This PR should get it passing again.
=> Fix broken links

core/xarray/computation-masking.ipynb, core/xarray/xarray-intro.ipynb
Fixes a couple of broken Xarray docs links that are causing the nightly build to fail.
=> Fix broken Xarray documentation links

myst.yml
Replaces links to `projectpythia-mystmd` with their `projectpythia` counterparts.
=> fix: update metadata URLs

core/cartopy/cartopy.ipynb, core/data-formats/netcdf-cf.ipynb, core/matplotlib.md, core/matplotlib/annotations-colorbars-layouts.ipynb, core/matplotlib/histograms-piecharts-animation.ipynb, core/matplotlib/matplotlib-basics.ipynb, core/numpy.md, core/numpy/intermediate-numpy.ipynb, core/numpy/numpy-basics.ipynb, core/numpy/numpy-broadcasting.ipynb, core/pandas/pandas.ipynb, core/xarray.md, core/xarray/dask-arrays-xarray.ipynb, core/xarray/xarray-intro.ipynb, foundations/getting-started-github.md, foundations/github/basic-git.md, foundations/github/contribute-to-pythia.md, foundations/github/git-branches.md, foundations/github/github-cloning-forking.md, foundations/github/github-issues.md, foundations/github/github-pull-request.md, foundations/github/github-repos.md, foundations/github/github-setup-advanced.md, foundations/github/github-workflows.md, foundations/github/review-pr.md, foundations/github/what-is-github.md
Closes #521 
This PR moves all logos and images below the main title for every page. This should resolve the duplicate title issue.
=> Fix duplicate titles

environment.yml, myst.yml
We want any interactive computing to default to the Pythia binder.
=> Link to Pythia binder

CONTRIBUTING.md, appendix/how-to-contribute.md, core/overview.md, foundations/conda.md, foundations/getting-started-jupyter.ipynb, foundations/github/basic-git.md, foundations/github/contribute-to-pythia.md, foundations/github/github-repos.md, foundations/how-to-run-python.md, foundations/jupyter.md, foundations/jupyterlab.ipynb, foundations/terminal.md, preamble/how-to-use.md
Internal link checker should catch these issues soon.
Related to
https://github.com/ProjectPythia/pythia-foundations/issues/549
=> Fix foundations links by removing '.html'
