_config.yml
_toc.yml
foundations/Hello.ipynb
foundations/basic-python.md

Just a minimal "Hello World" example

Add some notebook content and a Binder link

---

.github/workflows/preview-book.yaml

Add jupyter book preview GitHub action

---

README.md
_config.yml
landing-page.md

I've added the CC-BY license to the landing page. Perhaps this should go in the LICENSE file? I'm not sure because I *think* GitHub may have special handling for the LICENSE file. Anyone Know?
Fixes #2

Added Creative Commons license (CC-BY 4.0) to landing page.

---

preamble/how-to-contribute.md

Just pointing people to the README on GitHub that already has some instructions on how to build the book from source.

Add some info to contribute page

---

foundations/getting-started-python.md
foundations/overview.md

Closes #59 
Just updating links and descriptions in the overview pages of the Foundational Skills section of the book.

Update overview pages for foundations section

---

core/numpy.md
core/overview.md
foundations/getting-started-python.md
foundations/overview.md

Link overview pages and suggest order

---

.github/CODEOWNERS

Make infrastructure team owners of `_templates/`.

Tweak CODEOWNERS

---

foundations/conda.md
foundations/how-to-run-python.md
foundations/jupyter.md
foundations/terminal.md

Some foundations content was added before we had a set template in mind. I am updating some of the files to have a proper overview, summary, what's next section etc. This PR so far has 4 files updated (conda.md, terminal.md, jupyter.md, and how-to-run-python.md). There are more files that I want to update in time.

Update some .md files in foundations to match template

---

core/cartopy.md
core/cartopy/cartopy.ipynb

Cartopy links

---

environment.yml

Update environment to install pythia-datasets from conda-forge

---

_config.yml

Per discussion on and closes #130

Remove Linkify from _config.yaml

---

.github/workflows/nightly-build.yaml

Addresses https://github.com/ProjectPythia/pythia-foundations/issues/174#issuecomment-966590412

Remove continue-on-error from nightly workflow

---

core/matplotlib.md

Fix matplotlib doc link

---

core/cartopy/cartopy.ipynb

This PR addresses the issues described in #206 .

Update cartopy.ipynb to shorten run time

---

foundations/getting-started-github.md

Improve the GitHub landing page

---

_config.yml

add YouTube navbar item

---

foundations/why-python.md

typo line 13

---

.pre-commit-config.yaml
_config.yml
core/data-formats/netcdf-cf.ipynb
core/datetime/datetime.ipynb
core/matplotlib/matplotlib-basics.ipynb
core/numpy/numpy-basics.ipynb
core/numpy/numpy-broadcasting.ipynb
core/xarray/computation-masking.ipynb
foundations/quickstart.ipynb
pyproject.toml

- Addresses https://github.com/ProjectPythia/pythia-foundations/pull/257#issuecomment-1095429683

unpin nbqa pre-commit hook's additional dependencies

---

_config.yml

This at least allows the check to proceed.

Replace linkcheck ignore with custom user agent

---

foundations/github/basic-git.md
foundations/github/git-branches.md
foundations/github/github-cloning-forking.md
foundations/github/github-pull-request.md
foundations/github/github-workflows.md

Changes based on my comment on #214.

GitHub content revision

---

_config.yml
core/overview.md

Related to https://github.com/ProjectPythia/projectpythia.github.io/pull/247/
This PR also fixes a stray broken link to the Resource Gallery.

add cookbooks to nav bar

---

core/xarray/enso-xarray.ipynb

Fix broken link to ENSO figure

---

.github/workflows/deploy.yaml
.github/workflows/link-checker.yaml
.github/workflows/nightly-build.yaml
.github/workflows/preview-book.yaml

Let's see if this resolves #360

Update workflows to use Mambaforge

---

environment.yml

Remove unneccesary xarray version pin

---

appendix/template.ipynb

Fixes a broken link that's been flagged by our link-checker, e.g. [here](https://github.com/ProjectPythia/pythia-foundations/actions/runs/4474568031/jobs/7863165555#step:7:385)

Fix broken link in template

---

core/cartopy.md
core/cartopy/cartopy.ipynb
core/datetime.md
core/datetime/datetime.ipynb
core/matplotlib.md
core/matplotlib/annotations-colorbars-layouts.ipynb
core/matplotlib/histograms-piecharts-animation.ipynb
core/matplotlib/matplotlib-basics.ipynb
core/numpy/numpy-broadcasting.ipynb
core/pandas.md

Addresses https://github.com/ProjectPythia/pythia-foundations/issues/337

Lily edits

---

foundations/github/github-setup-advanced.md

broken link is blocking PR #388 
fixing it here

fix broken link

---

appendix/template.ipynb

Fixed header issue in template

---

_config.yml
_templates/footer-extra.html

Closes https://github.com/ProjectPythia/pythia-foundations/issues/397 partially
Motivation: Tutorial documentation often introduces new concepts or processes, and users may already be grappling with understanding unfamiliar information. A clean UI reduces cognitive load by simplifying the visual presentation and reducing unnecessary complexity. By minimizing distractions and focusing on essential elements, a clean UI helps users better absorb the tutorial content and decreases mental strain.

Move license to footer

---

CITATION.cff
_toc.yml
landing-page.md
preamble/how-to-cite.md

This PR adds detailed instructions on how to cite the book.
Also adds the DOI badge to the landing page, and incorporates the permanent DOI into the citation.cff file
Addresses #396

Add a "how to cite" section

---

_config.yml

Switch binder link to new Pythia binder, mybinder.org is not functional right now.

Switch to new Pythia binder

---

preamble/how-to-use.md

Addresses #404 
(no need to discuss authentication for now since we have disabled that for hackathon week)

Update binder link in "how to"

---

README.md

Remove line break so badges line up

---

core/data-formats/netcdf-cf.ipynb

- Fixes `long_name` of `lon_var` and `lat_var` in netcdf-cf.ipynb
- Changes `latitude` to `latitude coordinate`
- Changes `longitude` to `longitude coordinate`

Updates auxiliary chordates in Data Format

---

_config.yml
environment.yml

Set flag so the build fails on notebook errors

---

CITATION.cff
_config.yml

See https://github.com/ProjectPythia/projectpythia.github.io/pull/347

Creates a blog link in navbar

---

CITATION.cff
_templates/footer-menu.html

Update footer with link to how-to-cite and replace GitHub discussions with Pangeo discourse.

How to cite

---

core/xarray/computation-masking.ipynb

Fix pandas link

---

core/xarray.md
core/xarray/xarray-intro.ipynb

Fix links to Xarray logo

---

environment.yml

Here is another attempt to force an image rebuild for our Binder to deal with #441

Set minimum version of setuptools in environment.yml

---

foundations/github/basic-git.md

First draft pull request. Added examples to Basic Version Control with Git > Git commands mini-reference section.

Added examples to Git commands mini-reference section

---

environment.yml
preamble/how-to-use.md

Update local environment installation and instructions

---

.github/workflows/trigger-book-build.yaml

Not sure if this was intentional

Update trigger-book-build.yaml to use ProjecPythia action instead of brian's personal

---

paper.md

Just fixing an oops in the JOSE manuscript file.

Remove fake author

---

README.md
landing-page.md

This PR just puts badges on the landing page and the README showing the status of our JOSE manuscript submission (and linking to the paper once it's published).

Add JOSE status badges
